Add new properties
waveaccounting/terraform-aws-chatbot-slack-configuration pull request #6
Opened 2022-01-03 11:52 UTC by shonansurvivors

Hi all,
I implement new properties of chatbot slack configuration, [`GuardrailPolicies` and `UserRoleRequired`](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-chatbot-slackchannelconfiguration.html#aws-resource-chatbot-slackchannelconfiguration-properties
). 
I think this wonderful module could be more useful.
Thank you.

## Internal Ticket: 

### Notes

* Terraform docs will be auto-generated by a Github action

### Testing

* Run `make alpha scope=<major|minor|patch>` to tag and publish an alpha version
* Update the `version = "..."` of your module usage to your published alpha version (eg. `version = "v2.2.0-alpha.1+9f2630a"`)
* Run `make plan` in the keller terraform workspace

### Checklist

* [ ] Run `make changelog scope=<major|minor|patch>`
* [ ] CHANGELOG.md: Adjust change notes as necessary

### Publishing

* [ ] Merge this Pull Request
* [ ] Run `git checkout master; git pull; make publish scope=<major|minor|patch>`

2022-01-03 14:26 UTC, mwarkentin requested changes
@shonansurvivors thanks for sending in this change. I think it looks good, just a small comment about the defaults in the cloudformation params. 

If there's a reason you think it makes sense to include please add and I'll take another look!

2022-01-03 14:26 UTC, mwarkentin commented on cloudformation.yml
> +    Default: arn:aws:iam::aws:policy/AdministratorAccess
I don't think we need to set a default here - since we have defaults set in terraform there should never be a case where we fall back to the CloudFormation default.

2022-01-03 14:26 UTC, mwarkentin commented on cloudformation.yml
> +    Default: false
Same here.

2022-01-03 15:57 UTC, shonansurvivors commented on cloudformation.yml
> +    Default: arn:aws:iam::aws:policy/AdministratorAccess
Initially, I tested using only this `cloudformation.yml`, so the defaults are still there.
I think you are indeed right. I will remove these defaults.

2022-01-03 16:02 UTC, shonansurvivors commented
@mwarkentin I fixed it. It would be nice if you could check again.

2022-01-03 20:14 UTC, mwarkentin commented
@shonansurvivors thanks, looks good. Let us do a bit of testing.

2022-01-03 21:21 UTC, mwarkentin commented
@shonansurvivors I've pushed an alpha release of the module up if you want to try it out:

```
  module "chatbot-slack-configuration" {
  source  = "waveaccounting/chatbot-slack-configuration/aws"
  version = "1.1.0-alpha.2+a88b844"
  # insert the 5 required variables here
}
```

2022-01-04 00:24 UTC, shonansurvivors commented
@mwarkentin thanks! I tried `terraform init`, but it resulted in a git error. This problem might be caused by my environment.

```
$ terraform init
Initializing modules...
Downloading registry.terraform.io/waveaccounting/chatbot-slack-configuration/aws 1.1.0-alpha.2+a88b844 for chatbot_slack_configuration_cost...
╷
│ Error: Failed to download module
│ 
│ Could not download module "chatbot_slack_configuration_cost" (main.tf:105) source code from "git::https://github.com/waveaccounting/terraform-aws-chatbot-slack-configuration?ref=v1.1.0-alpha.2+a88b844": error downloading
│ 'https://github.com/waveaccounting/terraform-aws-chatbot-slack-configuration?ref=v1.1.0-alpha.2+a88b844': /usr/local/bin/git exited with 1: error: pathspec 'v1.1.0-alpha.2 a88b844' did not match any file(s) known to git
│ .
╵
```

```
# from my main.tf
module "chatbot_slack_configuration_cost" {
  source  = "waveaccounting/chatbot-slack-configuration/aws"
  version = "1.1.0-alpha.2+a88b844"

  configuration_name = "cost"
  iam_role_arn       = aws_iam_role.chatbot_cost.arn
  logging_level      = "ERROR"
  slack_channel_id   = aws_ssm_parameter.slack_channel_id.value
  slack_workspace_id = aws_ssm_parameter.slack_workspace_id.value

  sns_topic_arns = [
    aws_sns_topic.budget.arn,
  ]
}
```

```
$ git --version
git version 2.34.1
$ terraform --version
Terraform v1.1.2
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.63.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
```

2022-01-04 01:08 UTC, mwarkentin commented
Sorry about that, was pulled straight from the registry autogenerated docs - I'll try it out tomorrow and see if I see the same thing.

2022-01-04 16:33 UTC, mwarkentin commented
@shonansurvivors I'm seeing the same issue, not sure why though.. still looking into it. :)

2022-01-04 16:54 UTC, shonansurvivors commented
@mwarkentin Actually, I found out about an hour ago that a new tag `v1.1.0-alpha.3` has been released. Then I tried `terraform init & apply` in my environment, and it worked. Thanks!

2022-01-04 16:55 UTC, mwarkentin commented
@shonansurvivors thanks! Do you want to test out the new params and let me know if they're working as expected for you?

2022-01-04 17:22 UTC, shonansurvivors commented
@mwarkentin I have tried the following and all worked well.
- If I didn't set either `var.guardrail_policies` or `user_role_required`, default values have been set for the Chatbot configuration.
- I set `["arn:aws:iam::aws:policy/ReadOnlyAccess"]` on `var.guardrail_policies`, then `Guardrail policies` of Chatbot config was exactly that.
- I set `true` on `user_role_required`, and `Channel role` of Chatbot config was `-`(null).

I think these are on spec of AWS.

2022-01-05 15:04 UTC, mwarkentin commented
It seems that the guardrail policy gets switched from `ProtectionPolicy` to `AdministratorPolicy` when left to the defaults.

Trying to see if there's a way to maintain the ProtectionPolicy for people who wouldn't want escalated privileges through chatbot.

2022-01-05 15:55 UTC, mwarkentin commented
I've opened AWS Support case `9445591681 ` to discuss.

2022-01-05 17:00 UTC, shonansurvivors commented
@mwarkentin I'm not sure if I'm understanding you, so could you let me know?

What are your concerns about the following?

---

First, apply below.

```
module "chatbot_slack_configuration" {
  source  = "waveaccounting/chatbot-slack-configuration/aws"
  version = "1.1.0-alpha.3"

  configuration_name = "foo"
  guardrail_policies = ["arn:aws:iam::aws:policy/ReadOnlyAccess"]
  //
}
```

Then, guardrails policies of Chatbot config have `ReadOnlyAccess`.

Next, apply below.

```diff
module "chatbot_slack_configuration" {
  source  = "waveaccounting/chatbot-slack-configuration/aws"
  version = "1.1.0-alpha.3"

  configuration_name = "foo"
- guardrail_policies = ["arn:aws:iam::aws:policy/ReadOnlyAccess"]
  //
}
```

Then, guardrails policies of Chatbot config don't keep `ReadOnlyAccess` but become `AdministratorAccess`.

---

If the above is correct, then I don't think it's good either.

On the other hand, if I give the property `GuardrailPolicies` an empty string, CloudFormation will give me an error...

2022-01-05 17:35 UTC, mwarkentin commented
@shonansurvivors just trying to understand the behaviour, figure out if we should follow the CloudFormation defaults, and what sort of guidance we should provide in the docs for people who don't want a wildcard guardrail out of the box. :)

I'm confirming with AWS support that the default "Protection Policy" == `ReadOnlyAccess`.

The alternative could be to default to the more secure `ReadOnlyAccess` and provide docs / an example showing how to upgrade to the `AdministratorAccess` policy.

2022-01-05 18:10 UTC, mwarkentin commented
Another test - configuring a new chatbot slack integration with the existing `1.0.0` module also configures Admin guardrails:

```
Guardrail policies
arn:aws:iam::aws:policy/AdministratorAccess
```

So protection policy was probably applied only to integrations which were already set up (and possibly unmodified since) before AWS rolled out their updated functionality.

2022-01-05 18:50 UTC, mwarkentin commented
@shonansurvivors based on my testing and investigation above, I'm good with merging this and releasing a new version of the module. Seems like a minor version bump (1.1.0) would make sense - do you want to add the changes to `CHANGELOG.md`?

I think we'll need to generate docs afterwards as external PRs may not have the GitHub token available to them. Looks like we also need to update the Checkov action as well, I'll open a separate issue to handle that.

2022-01-06 00:59 UTC, shonansurvivors commented
@mwarkentin thank you for investigating. I learned a lot.

I'm not confident in my English, so it would be very nice if you could come up with a sentence plan for `CHANGELOG.md`.

2022-01-06 01:34 UTC, mwarkentin commented
Sure thing, I think we can get this merged and then I'll add the change log, etc

2022-01-06 01:34 UTC, mwarkentin approved these changes
LGTM

2022-01-07 20:19 UTC, apriljo approved these changes

2022-01-07 20:20 UTC, merged

2022-01-07 20:31 UTC, mwarkentin commented
@shonansurvivors we've just pushed [1.1.0](https://registry.terraform.io/modules/waveaccounting/chatbot-slack-configuration/aws/latest) to the terraform registry.. thanks again for your help!

2022-01-08 03:17 UTC, shonansurvivors commented
@mwarkentin I'm glad this module is more useful. I will introduce it to my friends in Japan. Thank you very much!